-- liquibase formatted sql

-- changeset alex:1
create table if not exists ads(
    pk                  int generated by default as identity primary key,
    price               int,
    description         varchar,
    author              int,
    title               varchar
);

-- changeset demaz:1
alter table ads rename column author to user_id;

-- changeset demaz:2
alter table ads rename column pk to id;