-- liquibase formatted sql

-- changeset alex:1
create table if not exists ads(
    pk                  int generated by default as identity primary key,
    price               int,
    description         varchar,
    author              int,
    title               varchar
);