-- liquibase formatted sql

-- changeset demaz:1
create table if not exists avatar(
    id              int generated by default as identity primary key,
    file_path     text not null,
    user_id         int not null
);