-- liquibase formatted sql

-- changeset demaz:1
create table if not exists comment(
    id                  int generated by default as identity primary key,
    text                text,
    create_at           bigint,
    ads_id              int,
    user_id             int
);

-- changeset demaz:2
alter table comment rename column create_at to created_at;

-- changeset demaz:3
alter table comment drop column created_at;
alter table comment add column created_at timestamp;