-- liquibase formatted sql

-- changeset demaz:1
create table if not exists image(
    id          int generated by default as identity primary key,
    file_path   text not null,
    ad_id       int not null
);

-- changeset demaz:2
alter table image alter column ad_id drop not null;